"""add tracking records

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-28 14:21:08.072147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.persistence.models


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('checkpoints_json', sa.String(), nullable=False),
    sa.Column('created_at', app.persistence.models.UTCDateTime(), nullable=False),
    sa.Column('last_refreshed_at', app.persistence.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_records')
    # ### end Alembic commands ###
